# .github/workflows/deploy.yml

name: Deploy Backend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build project
      - name: Build project
        run: npm run build

      # Step 5: Deploy to VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            echo "👉 Navigating to backend directory..."
            cd /www/wwwroot/backend/MirexaStoreBackend

            echo "👉 Pulling latest changes from Git..."
            git reset --hard
            git pull origin main

            echo "👉 Installing production dependencies..."
            npm install --omit=dev

            echo "👉 Restarting backend with PM2..."
            /home/yeasin_sarkar/.nvm/versions/node/v22.18.0/bin/pm2 describe mirexa-backend > /dev/null \
            && /home/yeasin_sarkar/.nvm/versions/node/v22.18.0/bin/pm2 restart mirexa-backend \
            || /home/yeasin_sarkar/.nvm/versions/node/v22.18.0/bin/pm2 start dist/server.js --name "mirexa-backend"
